[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[[services]]
name = "api"
target = "api-runner"

[services.api]
port = 4000
internalPort = 4000
protocol = "http"
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services.api.domains]]
domain = "${RAILWAY_SERVICE_API_URL}"

[[services]]
name = "worker"
target = "worker-runner"

[services.worker]
# Worker doesn't expose HTTP by default
# Enable health check if needed
# port = 3001
# healthcheckPath = "/health"