[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build:api && pnpm build:worker"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3